/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package game;

import javax.swing.JOptionPane;

/**
 *
 * @author jaypr
 */
public class Game1 extends javax.swing.JFrame {

    /** Creates new form Game1 */
    public Game1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlBoard = new javax.swing.JPanel();
        btn00 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        lblPlayerPlaying = new javax.swing.JLabel();
        lblPlayer1Score = new javax.swing.JLabel();
        lblPlayer2Score = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game");
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel2.setText("GAME FOR MASTI");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("P1 Symbol=o , P2 Symbol=x");

        pnlBoard.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 51), null));
        pnlBoard.setLayout(new java.awt.GridLayout(3, 3));

        btn00.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn00);

        btn01.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn01);

        btn02.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn02);

        btn10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn10);

        btn11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn11);

        btn12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn12);

        btn20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn20);

        btn21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn21);

        btn22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn22);

        lblPlayerPlaying.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPlayerPlaying.setText("Player playing :  1");

        lblPlayer1Score.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPlayer1Score.setText(" Player P1 = 0");

        lblPlayer2Score.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPlayer2Score.setText("Player P2 = 0");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Reload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem2.setText("Close");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(72, 72, 72)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlayerPlaying)
                            .addComponent(lblPlayer1Score)
                            .addComponent(lblPlayer2Score))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(pnlBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblPlayerPlaying)
                        .addGap(40, 40, 40)
                        .addComponent(lblPlayer1Score)
                        .addGap(27, 27, 27)
                        .addComponent(lblPlayer2Score)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(Game1.this, "App developed by : jay prakash");
           
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        turn=0;
        p1score=0;
        p2score=0;
        
        unlockBoard();
        
        lblPlayer1Score.setText("p1 score : 0");
        lblPlayer2Score.setText("p2 score : 0");
        
        lblPlayerPlaying.setText("Player Playing :"+(turn+1));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        unlockBoard();
        turn=0;
        lblPlayerPlaying.setText("Player Playing :"+(turn+1));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        // TODO add your handling code here
        if(turn%2==0){
            //p1 code
            btn00.setEnabled(false);
            btn00.setText("o");
            board[0][0]='o';
            if(checkwinner('o')){
                lockBoard();
                p1score++;
                lblPlayer1Score.setText("p1 score :"+p1score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
        else{
            //p2 code
             btn00.setEnabled(false);
            btn00.setText("x");
            board[0][0]='x';
            if(checkwinner('x')){
                lockBoard();
                p2score++;
                lblPlayer2Score.setText("p2 score :"+p2score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
    }//GEN-LAST:event_btn00ActionPerformed

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        // TODO add your handling code here:
        if(turn%2==0){
            //p1 code
            btn01.setEnabled(false);
            btn01.setText("o");
            board[0][1]='o';
            if(checkwinner('o')){
                lockBoard();
                p1score++;
                lblPlayer1Score.setText("p1 score :"+p1score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
        else{
            //p2 code
             btn01.setEnabled(false);
            btn01.setText("x");
            board[0][1]='x';
            if(checkwinner('x')){
                lockBoard();
                p2score++;
                lblPlayer2Score.setText("p2 score :"+p2score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        // TODO add your handling code here:
        if(turn%2==0){
            //p1 code
            btn02.setEnabled(false);
            btn02.setText("o");
            board[0][2]='o';
            if(checkwinner('o')){
                lockBoard();
                p1score++;
                lblPlayer1Score.setText("p1 score :"+p1score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
        else{
            //p2 code
             btn02.setEnabled(false);
            btn02.setText("x");
            board[0][2]='x';
            if(checkwinner('x')){
                lockBoard();
                p2score++;
                lblPlayer2Score.setText("p2 score :"+p2score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
        if(turn%2==0){
            //p1 code
            btn10.setEnabled(false);
            btn10.setText("o");
            board[1][0]='o';
            if(checkwinner('o')){
                lockBoard();
                p1score++;
                lblPlayer1Score.setText("p1 score :"+p1score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
        else{
            //p2 code
             btn10.setEnabled(false);
            btn10.setText("x");
            board[1][0]='x';
            if(checkwinner('x')){
                lockBoard();
                p2score++;
                lblPlayer2Score.setText("p2 score :"+p2score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
        if(turn%2==0){
            //p1 code
            btn11.setEnabled(false);
            btn11.setText("o");
            board[1][1]='o';
            if(checkwinner('o')){
                lockBoard();
                p1score++;
                lblPlayer1Score.setText("p1 score :"+p1score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
        else{
            //p2 code
             btn11.setEnabled(false);
            btn11.setText("x");
            board[1][1]='x';
            if(checkwinner('x')){
                lockBoard();
                p2score++;
                lblPlayer2Score.setText("p2 score :"+p2score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
        if(turn%2==0){
            //p1 code
            btn12.setEnabled(false);
            btn12.setText("o");
            board[1][2]='o';
            if(checkwinner('o')){
                lockBoard();
                p1score++;
                lblPlayer1Score.setText("p1 score :"+p1score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
        else{
            //p2 code
             btn12.setEnabled(false);
            btn12.setText("x");
            board[1][2]='x';
            if(checkwinner('x')){
                lockBoard();
                p2score++;
                lblPlayer2Score.setText("p2 score :"+p2score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        // TODO add your handling code here:
        if(turn%2==0){
            //p1 code
            btn20.setEnabled(false);
            btn20.setText("o");
            board[2][0]='o';
            if(checkwinner('o')){
                lockBoard();
                p1score++;
                lblPlayer1Score.setText("p1 score :"+p1score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
        else{
            //p2 code
             btn20.setEnabled(false);
            btn20.setText("x");
            board[2][0]='x';
            if(checkwinner('x')){
                lockBoard();
                p2score++;
                lblPlayer2Score.setText("p2 score :"+p2score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        // TODO add your handling code here:
        if(turn%2==0){
            //p1 code
            btn21.setEnabled(false);
            btn21.setText("o");
            board[2][1]='o';
            if(checkwinner('o')){
                lockBoard();
                p1score++;
                lblPlayer1Score.setText("p1 score :"+p1score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
        else{
            //p2 code
             btn21.setEnabled(false);
            btn21.setText("x");
            board[2][1]='x';
            if(checkwinner('x')){
                lockBoard();
                p2score++;
                lblPlayer2Score.setText("p2 score :"+p2score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        // TODO add your handling code here:
        if(turn%2==0){
            //p1 code
            btn22.setEnabled(false);
            btn22.setText("o");
            board[2][2]='o';
            if(checkwinner('o')){
                lockBoard();
                p1score++;
                lblPlayer1Score.setText("p1 score :"+p1score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
        else{
            //p2 code
             btn22.setEnabled(false);
            btn22.setText("x");
            board[2][2]='x';
            if(checkwinner('x')){
                lockBoard();
                p2score++;
                lblPlayer2Score.setText("p2 score :"+p2score);
                        
            }
            turn++;
            lblPlayerPlaying.setText("Player Playing : "+((turn%2)+1));
        }
    }//GEN-LAST:event_btn22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game1().setVisible(true);
            }
        });
    }
    void lockBoard()
    {
        for(int i=0;i<9;i++)
        {
            pnlBoard.getComponent(i).setEnabled(false);
        }
    }
    
    void unlockBoard(){
       for(int i=0;i<9;i++)
        {
            pnlBoard.getComponent(i).setEnabled(true);
        } 
       btn00.setText("");
       btn10.setText("");
       btn01.setText("");
       
       btn02.setText("");
       btn11.setText("");
       btn12.setText("");
       
       btn20.setText("");
       btn21.setText("");
       btn22.setText("");
       btn00.setText("");
       
       turn = 0;
       for(int i=0;i<3;i++){
           for(int j=0;j<3;j++){
            board[i][j]=' ';
       }
    }
    }
    

    boolean checkwinner(char symbol){
        for(int i=0;i<3;i++){
            // row winner check
            if((board[i][0]==symbol)&&(board[i][1]==symbol)&&(board[i][2]==symbol)){
                return true;
            }
            // column winner check
            if((board[0][i]==symbol)&&(board[1][i]==symbol)&&(board[2][i]==symbol)){
                return true;
            }
        }
        // left top diagonal
        if((board[0][0]==symbol)&&(board[1][1]==symbol)&&(board[2][2]==symbol)){
                return true;
        }
        //top right
        if((board[0][2]==symbol)&&(board[1][1]==symbol)&&(board[2][0]==symbol)){
                return true;
        }
        return false;
    }
    
 
    char [][]board = new char[3][3];
    int turn=0;
    int p1score=0;
    int p2score=0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblPlayer1Score;
    private javax.swing.JLabel lblPlayer2Score;
    private javax.swing.JLabel lblPlayerPlaying;
    private javax.swing.JPanel pnlBoard;
    // End of variables declaration//GEN-END:variables

}
